FROM registry.cern.ch/cmsweb/dmwm-base:20250506.1
MAINTAINER Valentin Kuznetsov vkuznet@gmail.com
# TAG to be passed at build time through `--build-arg TAG=<PYPI_TAG>`. Default: None
ARG TAG=None
ARG REPO=None

## from pypi
#RUN pip install mspileup==$TAG
# from src
ENV WMA_PKG=mspileup
ENV REPO=mapellidario
ADD wmcore_install_fromsrc.sh ${WMA_ROOT_DIR}/wmcore_install_fromsrc.sh
# Install the requested WMA_TAG.
RUN ${WMA_ROOT_DIR}/wmcore_install_fromsrc.sh -t ${TAG} -p ${WMA_PKG} -r ${REPO}

#RUN sed -i -e "s,-config.py,-config-pielup.py,g" /data/run.sh
#RUN sed -i -e "s,config.py,config-pielup.py,g" /data/manage
ENV WDIR=/data
ENV USER=_reqmgr2ms
RUN useradd ${USER} && install -o ${USER} -d ${WDIR}
RUN echo "%$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER ${USER}
RUN sudo chown -R $USER.$USER $WDIR
WORKDIR $WDIR
CMD ["python3"]
