FROM registry.cern.ch/cmsweb/dmwm-base:20250506.1
MAINTAINER Valentin Kuznetsov vkuznet@gmail.com
# TAG to be passed at build time through `--build-arg TAG=<PYPI_TAG>`. Default: None
ARG TAG=None
ARG REPO=None

## from pypi
#RUN pip install reqmon==$TAG
# from src
ENV WMA_PKG=reqmon
ADD wmcore_install_fromsrc.sh ${WMA_ROOT_DIR}/wmcore_install_fromsrc.sh
# Install the requested WMA_TAG.
RUN ${WMA_ROOT_DIR}/wmcore_install_fromsrc.sh -t ${TAG} -p ${WMA_PKG} -r ${REPO}

ENV WDIR=/data
ENV USER=_t0_reqmon
RUN useradd ${USER} && install -o ${USER} -d ${WDIR}
RUN echo "%$USER ALL=(ALL) NOPASSWD:ALL" >> /etc/sudoers
USER ${USER}
RUN sudo chown -R $USER.$USER $WDIR
WORKDIR $WDIR
RUN sed -i -e "s,srv=.*,srv=t0_reqmon,g" run.sh
CMD ["python3"]
